Thanks to...

SILME - Servicio de Informática Local de Menorca
BricoGeek
MABRIAN
IME - Institut Menorquí d'Estudis
Joventut Aj. Maó
Joventut Aj. Es Castell
Binary Menorca

...for funding this project.
